[package]
name = "preview-builder"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
image.workspace = true
mcap = { workspace = true, features = ["lz4", "zstd"] }
memmap2.workspace = true
serde_json.workspace = true
viewer-core = { path = "../../crates/viewer-core" }
viewer-preview-mcap = { path = "../../crates/viewer-preview-mcap" }

[[bin]]
name = "preview-builder"
path = "src/main.rs"
