[package]
name = "viewer-native"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
ros2-live = ["dep:rclrs"]

[dependencies]
anyhow.workspace = true
bev-renderer = { path = "../../crates/bev-renderer" }
egui.workspace = true
egui_plot.workspace = true
egui-wgpu.workspace = true
egui-winit.workspace = true
env_logger.workspace = true
log.workspace = true
memmap2.workspace = true
mcap = { workspace = true, features = ["lz4", "zstd"] }
pollster.workspace = true
scene-renderer = { path = "../../crates/scene-renderer" }
serde.workspace = true
serde_json.workspace = true
wgpu.workspace = true
winit.workspace = true
viewer-core = { path = "../../crates/viewer-core" }
viewer-layout = { path = "../../crates/viewer-layout" }
viewer-preview-mcap = { path = "../../crates/viewer-preview-mcap" }
viewer-renderer = { path = "../../crates/viewer-renderer" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rclrs = { version = "=0.7.0", optional = true }

[[bin]]
name = "viewer-native"
path = "src/main.rs"
